//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Punetor
    {
        public int PunetorID { get; set; }
        public string Emri { get; set; }
        public string Pozicion { get; set; }
        public string Office { get; set; }
        public Nullable<int> Mosha { get; set; }
        public Nullable<int> Rroga { get; set; }
    }
}
